### ISSUE TITLE
Conflicting dependencies

### ISSUE THREAD

**Issue by Daniel-van-Dijk** [fengranMark/PersonalizedCIR#2]
Hi, 

Interesting paper! 

I don't think the dependencies are correct:

INFO: pip is looking at multiple versions of pyserini to determine which version is compatible with other requirements. This could take a while.
**ERROR: Cannot install pyserini==0.16.0 and transformers==4.2.0 because these package versions have conflicting dependencies.**

The conflict is caused by:
    The user requested transformers==4.2.0
    pyserini 0.16.0 depends on transformers>=4.6.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

Is it safe to just update to the latest versions?

**Comment by fengranMark** [comment]
Hi, thank you for your observation. I think upgrading the transformer will not affect anything. Just keep the pyserini can work.
